use_frameworks!

platform :ios, '8.0'

target 'HBWKWebView_Example' do
  pod 'HBWKWebView', :path => '../'

  target 'HBWKWebView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
